#!/usr/bin/env bash

# Source this file prior to running the pipeline.

# Custom commands to set up environment.
module load java
module load singularity

##################################
# Required environment variables #
##################################

# Path to checkout of this code:
export CODEX_PIPELINE_CODEBASE=

# Path to top-level directory containing raw data to process.
export SUBS_DIR=

# Path to directory to map to to the /lab/data directory inside the Cytokit
# container
export CYTOKIT_DATA_DIR=
